### ISSUE TITLE
Add anti-rotation exercises

### ISSUE THREAD

**Issue by andrico1234** [andrico1234/calisthenics-skills#67]
Add pallof press + copenhagen plank exercises

https://www.reddit.com/r/bodyweightfitness/wiki/exercises/core#wiki_anti-rotation

Progression should be as follows:

Banded Pallof Press -> Knee Copenhagen Plank -> Side Plank* -> Copenhagen Plank -> Copenhagen Plank w/Movement

*Consider moving Side Plank from where it currently exists in the tree, to here

**Comment by andrico1234** [comment]
@suhaga15 Any content and videos that you write for the exercises, post here for review

**Comment by suhaga15** [comment]
Banded Pallof Press:
Attach a resistance band to a fixed post and stand holding the free end of the resistance band such that the post is to one of your sides. Move the band away from and towards your body for reps while keeping the core braced and arms as close to your body as possible and avoiding any sort of rotation at the hip or shoulder. Video: https://www.youtube.com/watch?v=AH_QZLm_0-s

Knee Copenhagen Plank:
Get into a side plank position with the plane of your body perpendicular to the ground and your forearm resting on the ground. Allow the knee, calf and foot of your upper leg to rest on a soft surface and keep the lower leg in front of you and balance that position with your core braced. The lower leg can rest on the ground and provide assistance if the movement is too hard with the lower leg not touching the ground. Video: https://www.youtube.com/watch?v=9jZrRO4ppeA

Side Plank:
Get into a position such that the plane of your body is perpendicular to the ground with your forearm and one of your feet resting on the ground. The other foot can rest on the foot on the ground. Hold this position for time by bracing your core and engaging your glutes. The position can be made harder by elevating either one or both feet. Video: https://www.youtube.com/watch?v=BBUEzjlwM1o

Copenhagen Plank:
Get into a side plank position with the upper foot elevated. Keep the lower leg bent at the knee and hold this position for time. Ensure that the core is braced tight and the glutes are also engaged. Video: https://www.youtube.com/watch?v=1NNqUQvMYGc (0:05-0:07)

Copenhagen Plank with Movement:
Once in the Copenhagen plank, move the foot of the bent leg from the back to the front and back again. Repeat this for reps. Video: https://www.youtube.com/watch?v=1NNqUQvMYGc (0:00 - 0:05)

**Comment by andrico1234** [comment]
@suhaga15 , thanks for this! Here are a few changes to some of the grammar:

*Banded Pallof Press:*
Attach a resistance band at chest height to a fixed post. With a distance of 6ft, face the post with your arms forward and turn your body 90 degrees clockwise. Holding the band, move your firt to and away from your chest. Do this in a slow and controlled manner and ensure that your core is engage and not twisting. Avoid any rotation at the hip or shoulder. Repeat for both sides of the body.

You can also add a timestamp to the youtube link like so: https://youtu.be/AH_QZLm_0-s?t=6

so that only relevant content is shown to the end user!

*Knee Copenhagen Plank:*
Get into a side plank position with your forearm resting on the ground. Allow the knee, calf and foot of your upper leg to rest on a soft surface and keep the lower leg in front of you. Remain balanced in this position with your core braced. If the movement is too hard, your lower leg can rest on the ground and provide assistance. Repeat for both sides.

*Side Plank:*
Move into a plank postion. Shift your weight onto a your right arm and rotate your body 90 ant-clockwise. Your feet should be stacked ontop of each other and the right side of your body should be facing the floor. Ensure core and glutes are engaged. Repeat for both sides of your body.

*Copenhagen Plank:*
Get into a side plank position. Adjust the exercise by lifting your lower leg off the group and bending the knee. Hold this position for time. Ensure that the core is braced tight and the glutes are engaged.

The copy for the last one is fine as it is!

Feel free to make any suggestions to my comments. If you're happy then make an MR with these additions. Please add the correct timestamps to the videos (you can do this from Youtube). And I'll give the MR a review!

Thanks
